/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musiktjeneste;

import java.io.*;

/**
 *
 * @author Julian
 */
public class Faner extends javax.swing.JPanel {

    /**
     * Creates new form Faner
     * @throws java.io.IOException
     */
    public Faner() throws IOException {
        initComponents();

        gUI1.ejer = this;
        startPanel1.ejer = this;
        montørPanel1.ejer = this;
  
        MusikAfspiller afspiller = new MusikAfspiller();
        gUI1.afspiller = afspiller;
        montørPanel1.afspiller = afspiller;
        startPanel1.afspiller = afspiller;
        afspiller.afspillerPanel = gUI1;
        afspiller.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        startPanel1 = new musiktjeneste.StartPanel();
        try {
            gUI1 = new musiktjeneste.GUI();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        try {
            montørPanel1 = new musiktjeneste.MontørPanel();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(503, 310));
        jTabbedPane1.addTab("Start", startPanel1);
        jTabbedPane1.addTab("Afspiller", gUI1);
        jTabbedPane1.addTab("Montør", montørPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private musiktjeneste.GUI gUI1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private musiktjeneste.MontørPanel montørPanel1;
    private musiktjeneste.StartPanel startPanel1;
    // End of variables declaration//GEN-END:variables

    /*
    * Metode til at skift mellem panelerne i fanebladet. 
    * Metoden sikrer velafgrænsede ansvarsområder for netop denne klasse.
    */
    public void skiftPanel(int n)
    {
        jTabbedPane1.setSelectedIndex(n);
    }
}
